### ISSUE TITLE
pod: command not found

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [bolav/fuse-cocoapods#3]
Hi,

I am adding cocoapods in my project using fuse-cocoapods. But every time I am getting this error.
`build/iOS/Preview/run.sh: line 9: pod: command not found`

I am adding `[Require("Cocoapods.Podfile.Target", "pod 'Mapbox-iOS-SDK', '~> 3.6'")]` in .uno file and Podfile is creating in Preview project with this dependency. But after that build is failed with an error.

Adding Cocoapods with `fusepm install https://github.com/bolav/fuse-cocoapods`

Using  
MacOS Seirra 10.12.6
Cocoapods version - 1.3.1

Please provide a solution for this.

Thanks

**Comment by bolav** [comment]
This repo is deprecated, after Fuse added native cocoapods support. Remove fuse-cocoapods from your project.
